### ISSUE TITLE
Broken links in README.md 

### ISSUE THREAD

**Issue by vdzhuvinov** [mwesten/StatamicV2-Highlight-Addon#2]
Hi Max,
The links in README.md about how to install the plug in seem to be broken (404).
Cheers,
Vlad

**Comment by mwesten** [comment]
Hi Vlad,
You are completely right....
They can be found now at: https://maxwesten.nl/projects/statamic-addons/highlight-v2-addon
Cheers,
Max

**Comment by vdzhuvinov** [comment]
Thank you! Works like a charm!
